{
  "hash": "387b2a0321db9754a643296f3b4e3694",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Water surface elevation at Venoco Bridge\"\nsubtitle: \"Week 1\"\ncategories: [tidyverse, dplyr, '$', '<-', '|>', pseudocode, min(), max(), nrow(), select(), mutate(), filter(), group_by(), summarize(), ungroup(), ggplot(), geom_point(), geom_line()]\n---\n\n\n# Summary\n\n## Guiding question\n\nHow does mean daily water surface elevation change over the course of a single water year at Venoco Bridge?\n\n## Data science tools\n\nTo answer this question, we will\n\n- use functions to manipulate objects or variables\n- use packages to take advantage of collections of specialized functions\n- extract variables from data using the `$` operator\n- assign values to objects using the `<-` operator\n- connect functions together using the `|>` operator\n- write _pseudocode_ to plan a workflow before coding it up\n- explore data using:\n  - `min()` to find the smallest number\n  - `max()` to find the largest number\n  - `nrow()` to count the number of rows in a data frame\n- wrangle data using:\n  - `select()` to select columns in a data frame\n  - `mutate()` to alter or add columns in a data frame\n  - `filter()` to filter rows based on column values\n- summarize data using:\n  - `group_by()`, `summarize()`, `ungroup()` to calculate summary statistics\n- visualize data using:\n  - `ggplot()` and its associated functions\n  \n# In-class code\n\n## 1. Set up\n\nA set up section is a nice location to read/load in packages and/or data that you'll use later in your script.  \n\nIt is best practice to start any script with all the materials you will need later on. This includes both your packages and your data.  \n\nStart this set up section by reading in the `tidyverse` package.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nThen, read in the data.  \n\nName the object `venoco_water`. Use the assignment operator (i.e. the left arrow operator) and the function `read_csv()` to store the values.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvenoco_water <- read_csv(\"venoco-water.csv\")\n```\n:::\n\n\n:::{.callout-note title=\"Functions to read in data\"}\n\nThere are many functions to read in data. We will use the `read_csv()` function from the `readr` package in the `tidyverse` because it is good  at understanding the values that are in each column of a file.\n\n:::\n\n## 2. Data exploration\n\nThen, examine at the data by:  \n\n1. clicking on the object in the Environment or running `View(venoco_water)` in the Console\n2. exploring the variables in the dataset using `str(venoco_water)` in the Console\n3. determining the object type by running `class(venoco_water)` in the Console\n\nThere are seven columns in this dataset:  \n\n::: {.column-margin}\nedited 2026-04-02:  \n\n- explaining column information in more detail\n- adding note about water year\n:::\n\n- `date`, which is a Date in ISO 8601 format representing date of water elevation observation\n- `time`, which is an `hms` object (hms stands for hours minutes seconds) representing time of water elevation observation\n- `comp_level_ft`, which is a numeric representing water elevation above sea level (not accounting for position of levelogger)\n- `temperature`, which is a numeric representing water temperature in ° Celsius\n- `year`, which is a numeric representing calendar year\n- `month`, which is a numeric representing calendar month\n- `wy`, which is a numeric representing water year\n\n:::{.callout-note title=\"What is a water year?\" collapse=\"true\"}\nThe year in the dataset and the water year are different in that the `year` column represents calendar year, while the `wy` column represents the water year. A water year is defined as starting on October 1st of one year and ending on September 30th of the next year. The 2025 water year in the dataset starts on October 1st, 2024 and ends on September 30th, 2025. \n\nA water year is a period of time [defined by the US Geological Survey](https://water.usgs.gov/nwc/explain_data.html) to account for precipitation falling in fall/winter that accumulates as snow and thus doesn't leave a watershed until the following spring/summer. At NCOS, it makes sense to consider trends in the time period of water years because the amount of rain that falls in the fall/winter is a strong determinant of water availability etc. for the spring and summer. The cycle starts again with rain in the fall and winter, which would mark the start of the next water year.\n:::\n\nHow many observations are in this dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(venoco_water)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 31974\n```\n\n\n:::\n:::\n\n\nThere are 31974 observations.  \n\nHow could you look at all the measurements of water elevation in this dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvenoco_water$comp_level_ft\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.00656168 1.19750656 1.19422572 1.18110236 1.18438320 1.18438320\n [7] 1.17782152 1.17454068 1.17454068 1.17454068 1.17782152 1.17125984\n[13] 1.17125984 1.17125984 1.17782152 1.17782152 1.18766404 1.19094488\n[19] 1.18766404 1.18766404 1.18110236 1.17782152 1.17454068 1.18110236\n[25] 1.17454068 1.18110236 1.17782152 1.17454068 1.18438320 1.18766404\n[31] 1.18438320 1.18766404 1.19750656 1.19094488 1.19750656 1.18438320\n[37] 1.19422572 1.19094488 1.18766404 1.18766404 1.18766404 1.17454068\n[43] 1.17782152 1.18110236 1.18766404 1.19422572 1.19422572 1.19750656\n[49] 1.19422572 1.19750656\n [ reached 'max' / getOption(\"max.print\") -- omitted 31924 entries ]\n```\n\n\n:::\n:::\n\n\nThis is useful, but not that informative. We can figure out some information about water elevation by applying functions.\n\nIn this case, we want to know what the lowest measurement of water elevation is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(venoco_water$comp_level_ft, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00656168\n```\n\n\n:::\n:::\n\n\nBut we also remember that the logger is slightly higher than sea level too.\n\nAccounting for that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(venoco_water$comp_level_ft, na.rm = TRUE) + 2.96\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.966562\n```\n\n\n:::\n:::\n\n\nThe lowest water elevation measured at Venoco bridge was 2.97 ft above sea level. \n\nWhat was the highest measurement of water elevation in the dataset, accounting for the elevation of the logger?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(venoco_water$comp_level_ft, na.rm = TRUE) + 2.96\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.859606\n```\n\n\n:::\n:::\n\n\nThe highest water elevation measured at Venoco bridge was 9.86 ft above sea level. \n\n## 3. Cleaning the data\n\nThis dataset includes a lot of columns and rows that we don't need.  \n\nWe can use functions from packages in the `tidyverse` to help us clean the data.  \n\nFirst, we could use `filter()` from the `dplyr` package in the `tidyverse` to filter the dataset to only include dates from the 2025 water year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwater1 <- filter(\n  venoco_water, # starting with venoco_water\n  wy == \"2025\" # only include observations from 2025 water year\n)\n```\n:::\n\n\nThen, we could use `mutate()` (also from `dplyr`) to create a new column in which the values are water elevations converted to meters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwater2 <- mutate(\n  water1, # starting with water1 data frame\n  comp_level_m = (comp_level_ft + 2.96) * 0.3048 # adding logger height and converting to meters from ft\n)\n```\n:::\n\n\nThen, we could use `select()` (also from `dplyr`) to choose the columns we \nneed to answer our guiding question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwater3 <- select(\n  water2, # starting with water2 data frame\n  date, comp_level_m, temperature # select columns of interest\n)\n```\n:::\n\n\n## 4. The pipe operator\n\nCreating multiple data frames (`water1`, `water2`, `water3`) as we did above can be tedious. Instead, you can use the pipe operator `|>` to chain functions together.  \n\nYou can think of the pipe operator as being a way of saying \"and then\".  \n\nIn the code we will write, we could say that we will:  \n \n- create a new object called `venoco_clean` from `venoco_water` and then...\n- filter to only include `wy` that matches `2025` and then...\n- mutate to create a new column called `comp_level_m` to add logger elevation \n  to `comp_level_ft` and convert to meters and then...\n- select the columns of interest (only `date`, `comp_level_m`, and `temperature`)\n\nThis is \"pseudocode\". Pseudocode looks different depending on the coding language, but in this class, \"pseudocode\" will refer to a bulleted list of steps you will later write in code.\n \nWriting pseudocode makes working with data much more straightforward. If you can plan out your code in plain language, it is easier to write the code (and troubleshoot when things go wrong!).\n \n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new object from venoco_water\nvenoco_clean <- venoco_water |> \n  # filter to only include 2025 water year\n  filter(wy == \"2025\") |> \n  # create a new column to convert water elevation in ft to meters\n  mutate(comp_level_m = (comp_level_ft + 2.96) * 0.3048) |> \n  # select columns of interest\n  select(date, comp_level_m, temperature)\n```\n:::\n\n\n## 5. Grouping data\n\nIn this dataset, each row is an observation of water level elevation at a particular time on a given day.  \n\nWhat if you want to visualize the mean water level for a given day?  \n  \nYou can add a function called `group_by()` from the `dplyr` package which allows you to \"group\" a data frame.  \nWhen you use `group_by()`, you are essentially telling R: there are \"groups\" in this data frame that I need to pay attention to.  \n\nWhen you pair `group_by()` with `summarize()` (also from `dplyr`), you can calculate summary statistics (e.g. calculate the mean daily water elevation) by each group (the date).\n\nIn this next section, we will:  \n\n- create a new object called `venoco_daily` from `venoco_clean`\n- group by date to\n- summarize (calculate) mean daily water level in m\n- ungroup the dataframe\n \n\n::: {.cell}\n\n```{.r .cell-code}\n# create new object from venoco_clean\nvenoco_daily <- venoco_clean |> \n  # group data frame by date\n  group_by(date) |> \n  # calculate mean water level in meters for a given day\n  summarize(mean_level_m = mean(comp_level_m, na.rm = TRUE)) |> \n  # ungroup the data frame\n  ungroup()\n```\n:::\n\n\n## 6. Visualizing data\n\nTo answer our question (How does mean daily water surface elevation change over the course of a single water year at Venoco Bridge?), we need to visualize the data in a timeseries plot.\n\nTimeseries plots have time on the x-axis and the variable of interest on the y-axis.\n\nTo visualize the data, we'll use `ggplot()` and its associated functions, which are all in the `ggplot2` package in the `tidyverse`.\n\nThe main parts of creating a plot in ggplot() are:  \n\n1. the **global call**: telling R that you want to use `ggplot()` by naming the\n   function\n2. the **data and mapping**: telling R the data frame you want to use (with the\n   argument `data = `) and the columns in that data frame to plot (with the\n   argument `mapping =` and the `aes()` function for the \"aesthetics\")\n3. the **geometries**: these are the shapes, lines, etc. in the plot. In this\n   case, we'll use two geometries: `geom_point()` to represent mean daily\n   water elevation and `geom_line()` to represent connections between each \n   day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# base layer: ggplot\nggplot(data = venoco_daily,\n       # x-axis should be date\n       # y-axis should be mean daily water elevation\n       mapping = aes(x = date,\n                     y = mean_level_m)) +\n  # first layer: points\n  geom_point(color = \"#287948\") +\n  # second layer: line\n  geom_line(color = \"#287948\") +\n  # relabeling x- and y-axes, adding title\n  labs(x = \"Date\",\n       y = \"Mean daily water elevation (m)\",\n       title = \"Water year 2025 (01 October 2024 - 30 September 2025)\") +\n  # using theme that is different from default\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](week-01_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## 7. Understanding trends\n\nWhat seasonal trends can you see?  \n\nHighs: February, March, April  \nDeclines: April to August  \nMore increases: August, September  \n\n## 8. Understanding warnings\n\nWhen you run the code to make the plot, you get a warning.\n\nThat warning means there is a missing value in your dataset that can't be plotted (because it's missing).\n\nYou can use the `is.na()` function to determine which values are missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.na(venoco_daily$mean_level_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE\n[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE\n[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE\n[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE\n[49] FALSE FALSE\n [ reached 'max' / getOption(\"max.print\") -- omitted 263 entries ]\n```\n\n\n:::\n:::\n\n\nThat's not super helpful.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvenoco_daily |> \n  filter(is.na(mean_level_m))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  date       mean_level_m\n  <date>            <dbl>\n1 2025-09-03          NaN\n```\n\n\n:::\n:::\n\n\nThe missing value is from 2025-09-03.\n\n**END OF CLASS MATERIALS**\n\n\n\n",
    "supporting": [
      "week-01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}