---
title: "Advanced elective"
date: 2026-06-10
---

# Advanced elective

For the advanced elective, you will create a piece of art or media that is relevant to your project. For example, you could make a short film introducing the plants of NCOS if your project is on vegetation; you could create a field guide zine if your project is on birds; you could create sculptures of ostracods and copepods if your project is on aquatic invertebrates; you could create a hand-drawn map of salinity in the slough if your project is on hydrology.

This elective is fairly loose to allow for maximum creative freedom; however, your elective must be _closely linked to your response variable_. For example, if your response variable is species richness, then your elective should include the diversity of species in some way. If your response variable is salinity in parts per thousand, then your elective should show how salinity is measured or understood.

# Completion of the advanced elective

**You may work in your project groups for this elective.** Check in with your fellow project members to discuss completion of this elective as a team.

If you decide to complete the advanced elective, you _must_ include a section in your work plan and your proposal to outline your ideas for your elective.

:::{.callout-tip title="Check in as soon as you can once you've decided on an idea."}

The sooner you get feedback, the sooner you can start - and the sooner you can pivot if you need to!

:::

# Timeline check in

For your project check in during week 8, you should have:

- a plan for completing the elective
- a draft/sketch/outline of the idea

# Presentation of the advanced elective

If _all_ members of your group opt in to completing the advanced elective, you may present on your elective _instead_ of your project results in week 10. However, this means your advanced elective must be completed by week 10.






