project:
  type: website
  output-dir: docs

website:
  title: "ENVS-193DD.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: in-class-materials.qmd
        text: In-class materials
      - href: system-checks.qmd
        text: System checks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



